apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: payment-api

  description: payment-api managed by the Internal Developer Platform

  tags:
    - aws
    - web-service
    - dev

  annotations:
    idp/status: active
    idp/environment: dev
    backstage.io/techdocs-ref: dir:../../../docs/payment-api

  links:
    - url: https://grafana.example.com/d/payment-api
      title: Grafana Dashboard
      icon: dashboard

    - url: https://github.com/saakibsheikh1/internal-developer-platform
      title: Repository
      icon: github

spec:
  type: service
  lifecycle: production
  owner: payments
